name: Quality

on: pull_request

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup
          
      - name: Run format check ğŸ–Œ
        run: bun run format:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run lint check ğŸ§¹
        run: bun run lint:check

  typescript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run type check ğŸ”
        run: bun run type:check

  spell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run spell check ğŸ“
        run: bun run spell:check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install Playwright browsers ğŸ­
        run: bunx playwright install chromium

      - name: Run tests ğŸ§ª
        run: bun run test